<?php
/**
 * Some helping functions
 *
 * @copyright   2011 [di] digitale informationssyteme
 * @version     $Id: $
 * @author      frank meyerer <meyerer@digi-info.de>
*/

/**
 *
 * Implementation of hook_node_api().
 *
 * @author     frank meyerer <meyerer@digi-info.de>
 */
function meyerer_addons_node_view($node, $view_mode, $langcode)
{
    if(isset($node->content['body']) && isset($node->field_firstblogpic['de'][0]['value']))
    {
        if($node->field_firstblogpic['de'][0]['value'] == 1)
        {
            $node->content['body'][0]['#markup'] = meyerer_addons_addPic2Para($node, $langcode);
        }
    }
}

/**
 *
 * Replaces the first <p> with <p><img ..... /> in the node body
 *
 * @author     frank meyerer <meyerer@digi-info.de>
 *
 * @param $node
 *   node object
 * @param $langcode
 *   language string
 * @return
 *   the node body
 */
function meyerer_addons_addPic2Para($node, $langcode)
{

    $content = $node->content['body'][0]['#markup'];

    if(isset($node->field_blogpic))
    {
        if(count($node->field_blogpic) > 0)
        {
            $pic = $node->field_blogpic[$langcode][0];

            $pic_render = theme('image_style', array('style_name' => 'blog_teaser',
                                               'path' => $pic['uri'],
                                               'alt' => $pic['alt'],
                                               'title' => $pic['title'],
                                               'attributes' => array('class' => 'imagefield-blog_teaser left')));

            $addon = l($pic_render, 'node/' . $node->nid, array('html' => array('html' => 'true')));

            $content = preg_replace("(<p>)", "<p>" . $addon, $content, 1);
        }
    }
    return $content;
}

/**
 *
 * Returns a rendered picture
 *
 * @author     frank meyerer <meyerer@digi-info.de>
 *
 * @param $fid
 *   File id
 * @return
 *   html image link
 */
function meyerer_addons_render_recentpics($fid = 0)
{
    $pic = file_load($fid);
    $pic_more = file_usage_list($pic);
    $nid = key($pic_more['file']['node']);
    $node_info = node_load($nid);

    foreach($node_info->field_blogpic['de'] as $k => $v)
    {
        if($v['fid'] == $fid)
        {
            $pic_info = $v;
            break;
        }
    }

    $pic_render = theme('image_style', array('style_name' => 'minithumb',
                                               'path' => $pic->uri,
                                               'alt' => $pic_info['alt'],
                                               'title' => $pic_info['title'],
                                               'attributes' => array('class' => 'imagefield-minithumb')));

    $link_render = l($pic_render, 'node/' . $node_info->nid, array('html' => array('html' => 'true')));

    return $link_render;
}

/**
 *
 * Define the "Rosengarten" MP3 block
 *
 * @author     frank meyerer <meyerer@digi-info.de>
 */
function meyerer_addons_block_info()
{
    $blocks['rosengarten_mp3'] = array(
        'info' => t('Rosengarten Mp3'),
        'cache' => DRUPAL_CACHE_GLOBAL,
        'status' => TRUE,
        'region' => 'sidebar_second', // Not usually provided.
        'visibility' => 1, // Not usually provided.
    );

    return $blocks;
}

/**
 *
 * Mp3 Player block output
 * Help: http://wpaudioplayer.com/standalone
 *
 * @author     frank meyerer <meyerer@digi-info.de>
 */
function meyerer_addons_block_view($delta = '')
{
    $block = array();

    switch ($delta)
    {
        case 'rosengarten_mp3':
            $block['subject'] = t('Oh you beautiful rose garden');

            drupal_add_js('sites/all/libraries/audio-player/audio-player.js');
            drupal_add_js('AudioPlayer.setup("sites/all/libraries/audio-player/player.swf",
                           {
                                width: 220,
                                transparentpagebg: "yes",
                                loader: "86110E"
                           });',
                           array('type' => 'inline', 'scope' => 'header')
            );

            $content  = '<p id="rosengarten_mp3">No Flash Plugin</p>';
            $content .= '<script type="text/javascript">';
            $content .= 'AudioPlayer.embed("rosengarten_mp3", {soundFile: "sites/default/files/audio/rosengarten.mp3", titles: "Oh du schöner Rosengarten (Volkslied aus Lothringen)"});';
            $content .= '</script>';

            $block['content'] = $content;
        break;
    }

    return $block;
}